name: Generate 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"  # daily at 18:00 UTC (11:30 PM IST)
  workflow_dispatch:        # allow manual trigger
  push:
    branches:
      - main

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate 3D Isometric Contribution Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: SakthivelMadhu
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          filename: profile-3d-contrib/profile-night-rainbow.svg
          config_timezone: Asia/Kolkata
          config_padding: 6%, 10%
